### ISSUE TITLE
changing PrometheusStatusResponseTimeBuckets does not work

### ISSUE THREAD

**Issue by christophbrejla** [ConSol/apache_mod_prometheus_status#3]
Hello,

i wanted to adjust the PrometheusStatusResponseTimeBuckets, but my setting is not working, instead always the default settings are being used. Other Settings that i have changed, like "PrometheusStatusLabelNames" and "PrometheusStatusLabelValues" are working. 

Please see my config entries below, which i added to the "apache2.conf". Do you have any idea why the adjusted setting wont take effect?

Thx, best regards

<IfModule !mod_prometheus_status.c>
  LoadModule prometheus_status_module /usr/lib/apache2/modules/mod_prometheus_status.so
< / IfModule>

PrometheusStatusEnabled               On
PrometheusStatusLabelNames            vhost;method;status;path;application
PrometheusStatusLabelValues           %v;%m;%s;%U;
PrometheusStatusTmpFolder             /tmp
PrometheusStatusResponseTimeBuckets   0.01;0.1;1;5;30;60
PrometheusStatusResponseSizeBuckets   1000;10000;100000;1000000;10000000;100000000

<Location /metrics>
  SetHandler prometheus-metrics
< / Location>

**Comment by sni** [comment]
there was a typo, should be fixed now. Thanks for reporting this.

**Comment by christophbrejla** [comment]
thanks for the fast fix i will try it.
