### ISSUE TITLE
Module logging format

### ISSUE THREAD

**Issue by rm-hull** [ConSol/apache_mod_prometheus_status#7]
Hi, 

Apache httpd error logs (by default) look like this:

```
[Mon Nov 06 13:37:48.635590 2023] [mpm_worker:notice] [pid 1:tid 140691984557952] AH00292: Apache/2.4.58 (Unix) configured -- resuming normal operations
```

This module exports log messages as follows:

```
[2023-11-06 13:37:48.593974][mod_prometheus_status][Info][pid:8][module.go:76] mod_prometheus_status v0.3.0 initialized - socket:/var/tmp/mtr.mCdcOh - uid:33 - gid:33 - build:0.3.0
```

Is it possible to fall in line with the common apache logging? Reason I ask is we export using fluentbit with a regex that extracts out the relevant fields for structured logging, and none of the mod_prometheus_status lines match the regex. Obviously I could extend the regex but it is fairly knarly as it is without trying to extend it.

Browsing the code, it looks to be this line that needs modifying: https://github.com/ConSol-Monitoring/apache_mod_prometheus_status/blob/master/cmd/mod_prometheus_status/logger.go#L14 - I'd be happy to supply a PR to do that if you're ok with what I'm proposing?

I guess the aim would be to rewrite the log message along the lines of:
```
[Mon Nov 06 13:37:48.593974 2023] [mod_prometheus_status:info] [pid 8:tid ???] [module.go:76] mod_prometheus_status v0.3.0 initialized - socket:/var/tmp/mtr.mCdcOh - uid:33 - gid:33 - build:0.3.0
```

Not too sure where/if the `tid` (thread id) is available in golang

**Comment by sni** [comment]
go does not expose the thread id easily. But i guess it's more important to match the date format, right?
I am totally fine with changing that.

**Comment by rm-hull** [comment]
Great - I'll have a go at assembling a PR for this then
